### PR TITLE
Add some nouns and adjectives

### PR DESCRIPTION
**Pull request by purenaturalism**
I've add some nouns for issue #4 and add some adjectives for issue #7.

### CODE REVIEW

**Comment by Shahenzi** [comment]
Just a heads up! Lines 119, 127, and 129 in the adjectives file are all the same word, "next"

**Comment by purenaturalism** [comment]
Okay. Fixed.

**Comment by chrisburgin95** [comment]
Hey! I merged in a few request before yours so now you seem to have a bit of a merge conflict. You do not have to but are welcome to resolve the conflict and I can merge in your request! Have a great day!

**Comment by purenaturalism** [comment]
Okay. I've fixed the conflicts.

**Pull request merged**
